### ISSUE TITLE
Composite Key Support

### ISSUE THREAD

**Issue by BrainBlasted** [TerminalDotRun/KeepassGtk#4]
Currently the program only allows users to have either a key file or password. Often people use databases with both

**Comment by baumkuchen42** [comment]
Well, to unlock a keepass2 database you only need one of both. We first focussed on the password method. If you have a keyfile plus a password for your keepass2 database you could now open it with your password only

**Comment by BrainBlasted** [comment]
> If you have a keyfile plus a password for your keepass2 database you could now open it with your password only

This is untrue. When you create a database using both a keyfile and password, the database uses the combination. If you do not have the keyfile the database will be interpreted as incorrect.

**Comment by FalkAlexander** [comment]
I have to investigate a little into that topic but this should be possible with the library we are using.

**Comment by BrainBlasted** [comment]
Right now the button in the switcher for composite keys is broken

**Comment by FalkAlexander** [comment]
Commit 2956b75354b4805bfebdbf38e439856a5f23994c introduced a new UI for composite keys.
Commit 086e9cf0add80e95dccd11802ee6001c5e41b86f reverted this for no reason.
Reintroduced now.
