### ISSUE TITLE
Opening Key Files Does Not Work

### ISSUE THREAD

**Issue by BrainBlasted** [TerminalDotRun/KeepassGtk#5]
Currently pressing the button to choose a key file has no action

**Comment by baumkuchen42** [comment]
That's because it's a feauture we planned for the future. As you can see our project is relatively young so we first want to implement the basics. The opining via keyfile is an extra feauture we want to concentrate on later

**Comment by FalkAlexander** [comment]
Will fix this in near future. This project is currently in early stage, I hope I can get this implemented soon.
